import '../styles/globals.css'

import React from 'react'

import Providers from '../utils/provider'

export const metadata = {
  title: 'Products | Humalect frontend assignment',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-background min-h-screen antialiased">
        <Providers>
          <div className="flex min-h-screen flex-col">{children}</div>
        </Providers>
      </body>
    </html>
  )
}
